#!/home/ubuntu/.nvm/versions/node/v6.11.2/bin/node

// Returns the paragraphs from a Wikipedia link, stripped of reference numbers.

let request = require("request");
let url = process.argv[2];

console.log(url);